name: prod-pipeline

on:
  push:
    branches:
      - prod
jobs:
  prod-pipeline:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./mindful-app

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run Angular tests
        run: npm test
